Yay, gcc compile. add pre-op and gocd to make sure to be in the right path
However, on Ubuntu (and on recent 11.04 in particular), one needs to be aware of:

- Ubuntu-specific default compiler flags
  (see https://wiki.ubuntu.com/CompilerFlags)
  '-U_FORTIFY_SOURCE' is needed for both CPLAGS and CPPFLAGS in order to avoid:
  /usr/include/bits/fcntl2.h:51:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments

- asm/errno.h moves around, as illustrated by http://old.nabble.com/-Bug-c%2B%2B-48879--New%3A-Compilation-cannot-find-file-asm-errno.h-td31547477.html, resulting in error:
  ' /usr/include/linux/errno.h:4:23: asm/errno.h: No such file or directory '
  However, a simple solution is given by http://emumiga.com/2011/05/15/ran-into-a-bug-in-ubuntu-11-04/
  Install gcc-multilib, that will make the symbolic link asm -> i386-linux-gnu/asm in /usr/include